### ISSUE TITLE
程序运行报错

### ISSUE THREAD

**Issue by sandyhouse** [PaddlePaddle/PLSC#61]
2020-05-22 16:49:30,924-INFO: User manually set optimizer.
Traceback (most recent call last):
  File "train_fp16.py", line 346, in <module>
    ins.train()
  File "/ssd2/wangjian/k8s_debug/plsc-env/python/lib/python2.7/site-packages/plsc/entry.py", line 907, in train
    dist_strategy=strategy)
  File "/ssd2/wangjian/k8s_debug/plsc-env/python/lib/python2.7/site-packages/plsc/entry.py", line 469, in build_program
    dist_optimizer.minimize(loss)
  File "/ssd2/wangjian/k8s_debug/plsc-env/python/lib/python2.7/site-packages/paddle/fluid/incubate/fleet/collective/__init__.py", line 420, in minimize
    no_grad_set=no_grad_set)
  File "/ssd2/wangjian/k8s_debug/plsc-env/python/lib/python2.7/site-packages/plsc/models/dist_algo.py", line 424, in minimize
    optimize_ops = self._optimizer.apply_gradients(scaled_params_grads)
  File "/ssd2/wangjian/k8s_debug/plsc-env/python/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 705, in apply_gradients
    optimize_ops = self._create_optimization_pass(params_grads)
  File "/ssd2/wangjian/k8s_debug/plsc-env/python/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 535, in _create_optimization_pass
    self._create_global_learning_rate()
  File "/ssd2/wangjian/k8s_debug/plsc-env/python/lib/python2.7/site-packages/paddle/fluid/optimizer.py", line 276, in _create_global_learning_rate
    "learning rate variable is create outside optimizer,"
TypeError: learning rate variable is create outside optimizer,can not create new learning rate variable for new program

**Comment by sandyhouse** [comment]
PLSC使用with fluid.program_guard语句设置了main_program覆盖default_main_program，所以在外部设置Optimizer的learning_rate出错。一种临时的解决方案是修改源码去掉with fluid.program_guard语句。
