### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by tianxingyzxq** [PaddlePaddle/PLSC#69]
File "/home/yx/anaconda3/lib/python3.7/site-packages/plsc/entry.py", line 982, in train
    acc5))
TypeError: unsupported format string passed to numpy.ndarray.__format__
有人遇到过吗

**Comment by sandyhouse** [comment]
用的是什么版本？

**Comment by tianxingyzxq** [comment]
paddle 1.8.1
plsc 0.1.1

**Comment by sandyhouse** [comment]
可以用master分支的代码，这个地方做过bug修复。
具体地，用python setup.py bdist_wheel --universal生成wheel包，然后安装。

**Comment by tianxingyzxq** [comment]
好的 我试试

**Comment by tianxingyzxq** [comment]
重新生成并安装后 训练出现如下错误
2020-07-14 10:41:35,323-WARNING: Your reader has raised an exception!
Exception in thread Thread-1:
TypeError: only size-1 arrays can be converted to Python scalars

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yx/anaconda3/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/yx/anaconda3/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/yx/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1156, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/home/yx/anaconda3/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/yx/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1136, in __thread_main__
    for tensors in self._tensor_reader():
  File "/home/yx/anaconda3/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 204, in __call__
    yield self._done()
  File "/home/yx/anaconda3/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 192, in _done
    return [c.done() for c in self.converters]
  File "/home/yx/anaconda3/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 192, in <listcomp>
    return [c.done() for c in self.converters]
  File "/home/yx/anaconda3/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 157, in done
    arr = np.array(self.data, dtype=self.dtype)
ValueError: setting an array element with a sequence.

Traceback (most recent call last):
  File "do_train.py", line 70, in <module>
    main()
  File "do_train.py", line 67, in main
    ins.train()
  File "/home/yx/anaconda3/lib/python3.7/site-packages/plsc/entry.py", line 986, in train
    for batch_id, data in enumerate(self.input_field.loader):
  File "/home/yx/anaconda3/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1102, in __next__
    return self._reader.read_next()
paddle.fluid.core_avx.EnforceNotMet:

**Comment by sandyhouse** [comment]
可以提供最小可复现代码和相应的数据吗，我们复现下该问题？

**Comment by tianxingyzxq** [comment]
代码和数据如附件
[report_paddle.zip](https://github.com/PaddlePaddle/PLSC/files/4918820/report_paddle.zip)

**Comment by tianxingyzxq** [comment]
在报错前打印出self.data 如下：
[(array([[[-0.11328125, -0.11328125, -0.11328125, ..., -0.48828125,
         -0.51171875, -0.48828125],
        [-0.10546875, -0.10546875, -0.11328125, ..., -0.48828125,
         -0.51171875, -0.48828125],
        [-0.11328125, -0.11328125, -0.11328125, ..., -0.49609375,
         -0.51171875, -0.50390625],
        ...,
        [-0.08203125, -0.04296875, -0.02734375, ..., -0.22265625,
         -0.25390625, -0.21484375],
        [-0.06640625, -0.04296875, -0.02734375, ..., -0.26171875,
         -0.27734375, -0.26953125],
        [-0.05859375, -0.04296875, -0.02734375, ..., -0.27734375,
         -0.28515625, -0.28515625]],

       [[-0.16015625, -0.16015625, -0.16015625, ..., -0.50390625,
         -0.52734375, -0.50390625],
        [-0.15234375, -0.15234375, -0.16015625, ..., -0.50390625,
         -0.52734375, -0.50390625],
        [-0.16015625, -0.16015625, -0.16015625, ..., -0.51171875,
         -0.52734375, -0.51953125],
        ...,
        [-0.18359375, -0.14453125, -0.12890625, ..., -0.46484375,
         -0.49609375, -0.45703125],
        [-0.16796875, -0.14453125, -0.12890625, ..., -0.49609375,
         -0.51171875, -0.50390625],
        [-0.16015625, -0.14453125, -0.12890625, ..., -0.51171875,
         -0.50390625, -0.50390625]],

       [[-0.34765625, -0.34765625, -0.34765625, ..., -0.49609375,
         -0.51953125, -0.49609375],
        [-0.33984375, -0.33984375, -0.34765625, ..., -0.49609375,
         -0.51953125, -0.49609375],
        [-0.34765625, -0.34765625, -0.34765625, ..., -0.50390625,
         -0.51953125, -0.51171875],
        ...,
        [-0.30859375, -0.26953125, -0.25390625, ..., -0.48046875,
         -0.51171875, -0.47265625],
        [-0.29296875, -0.26953125, -0.25390625, ..., -0.51171875,
         -0.52734375, -0.51953125],
        [-0.28515625, -0.26953125, -0.25390625, ..., -0.52734375,
         -0.52734375, -0.52734375]]], dtype=float32), 2)]

**Comment by sandyhouse** [comment]
好的，我们先本地复现下看看。

**Comment by tianxingyzxq** [comment]
@sandyhouse 提供的能复现吗，还需要其他的什么信息？

**Comment by sandyhouse** [comment]
python2下无法复现，python3可以复现，看着像是兼容性问题，我再确认下。

**Comment by sandyhouse** [comment]
已经提了bug个修复，可以拉取最新的master分支试一试。感谢反馈。 @tianxingyzxq

**Comment by tianxingyzxq** [comment]
拉取了master了，一样的报错信息 @sandyhouse

**Comment by tianxingyzxq** [comment]
看了下bug fix中的代码 是不是提交错代码了。。 @sandyhouse

**Comment by sandyhouse** [comment]
不好意思，确实是提错代码了，已修正。麻烦再重新拉取下吧，抱歉。

**Comment by tianxingyzxq** [comment]
能运行了，非常感谢！ @sandyhouse

**Comment by sandyhouse** [comment]
This issue has been fixed by the commit https://github.com/PaddlePaddle/PLSC/commit/069d8b09d7afc341b483ae82cf85391eb6aff44d. I will close this issue. Reopen it if you have any further questions.
